### ISSUE TITLE
最新版本编译不通过

### ISSUE THREAD

**Issue by lexkong** [seanchann/sample-apiserver#1]
是没有编译通过：
../../pkg/registry/sample/rest/storage_sample.go:23:2: cannot find package "github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage" in any of:
        /data/home/lkong/workspace/golang/src/github.com/seanchann/sample-apiserver/vendor/github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage (vendor tree)
        /usr/local/go1.11.2/src/github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage (from $GOROOT)
        /data/home/lkong/workspace/golang/src/github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage (from $GOPATH)
../../pkg/registry/sample/rest/storage_sample.go:24:2: cannot find package "github.com/seanchann/sample-apiserver/pkg/registry/sample/user/storage" in any of:
        /data/home/lkong/workspace/golang/src/github.com/seanchann/sample-apiserver/vendor/github.com/seanchann/sample-apiserver/pkg/registry/sample/user/storage (vendor tree)
        /usr/local/go1.11.2/src/github.com/seanchann/sample-apiserver/pkg/registry/sample/user/storage (from $GOROOT)
        /data/home/lkong/workspace/golang/src/github.com/seanchann/sample-apiserver/pkg/registry/sample/user/st

**Comment by seanchann** [comment]
enable golang module and rebuild it with refresh code

**Comment by seanchann** [comment]
add missing file and fix gitignore bug

**Comment by lexkong** [comment]
thanks very much! i can compile it now.
