### ISSUE TITLE
cannot find package "github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage"

### ISSUE THREAD

**Issue by lexkong** [seanchann/sample-apiserver#2]
$ go build -v .
../../pkg/registry/sample/rest/storage_sample.go:23:2: cannot find package "github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage" in any of:
	/data/home/lkong/Workspace/golang/src/github.com/seanchann/sample-apiserver/vendor/github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage (vendor tree)
	/usr/local/go1.11.2/src/github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage (from $GOROOT)
	/data/home/lkong/Workspace/golang/src/github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage (from $GOPATH)
../../pkg/registry/sample/rest/storage_sample.go:24:2: cannot find package "github.com/seanchann/sample-apiserver/pkg/registry/sample/user/storage" in any of:
	/data/home/lkong/Workspace/golang/src/github.com/seanchann/sample-apiserver/vendor/github.com/seanchann/sample-apiserver/pkg/registry/sample/user/storage (vendor tree)
	/usr/local/go1.11.2/src/github.com/seanchann/sample-apiserver/pkg/registry/sample/user/storage (from $GOROOT)
	/data/home/lkong/Workspace/golang/src/github.com/seanchann/sample-apiserver/pkg/registry/sample/user/storage (from $GOPATH)

this error reported that there is no `github.com/seanchann/sample-apiserver/pkg/registry/sample/test/storage` package in the newest code, i guess you have add test or something in .gitignore file, when push the local repository they not pushed into github repo.

**Comment by seanchann** [comment]
don't open same issue!
